### ISSUE TITLE
DANGEROUS DO NOT USE

### ISSUE THREAD

**Issue by San-Jeevan** [RGBboy/mongodb-s3-backup#13]
As foolish as I am I ran this on my production. It locked my database for all writes.
I had to spend few minutes googling how to unlock it.
while alot of people complained.

SUCKS

**Comment by RGBboy** [comment]
This is due to an issue with older versions of mongodb where in order to save an accurate snapshot of the DB you have to lock it.

This library was built for my specific use case. I recommend writing your own if you would like a different behaviour.
