### ISSUE TITLE
us-east-1

### ISSUE THREAD

**Issue by asanchezdelc** [RGBboy/mongodb-s3-backup#3]
Just a heads up that the script won't work for us-east-1 region. 

Here's my fix:

```
curl -X PUT \
--header "Host: $S3_BUCKET.s3.amazonaws.com" \
--header "Date: $HEADER_DATE" \
--header "content-type: $CONTENT_TYPE" \
--header "Content-MD5: $CONTENT_MD5" \
--header "Authorization: AWS $AWS_ACCESS_KEY:$SIGNATURE" \
--upload-file $DIR/backup/$ARCHIVE_NAME \
https://$S3_BUCKET.s3.amazonaws.com/$ARCHIVE_NAME
```

**Comment by fizerkhan** [comment]
+1

**Comment by seanfuture** [comment]
+1 .. Changed to us-west-2 and it then worked .. Thanks for script

**Comment by collinbrewer** [comment]
+1 I had to do the same.  I was getting a "Could not resolve host", so I pulled the region and all was well.

Thanks for the script.

**Comment by RGBboy** [comment]
This library was built for my specific use case. I recommend writing your own if you would like a different behaviour. Feel free to fork this as a base.
