### ISSUE TITLE
S3 folders

### ISSUE THREAD

**Issue by gdelgado** [RGBboy/mongodb-s3-backup#4]
Hello,

So it seems the script will only backup to the root of an S3 bucket and not folder structures within the bucket?

Thanks..

**Comment by iplog** [comment]
I got the same issue. This is related to the way the signature is created

https://github.com/RGBboy/mongodb-s3-backup/blob/23f140cddfd15b1e756f84287a1ffc9a428163bc/backup.sh#L104

At the moment the string to sign is:

``` bash
STRING_TO_SIGN="PUT\n$CONTENT_MD5\n$CONTENT_TYPE\n$HEADER_DATE\n/$S3_BUCKET/$ARCHIVE_NAME"
```

To have upload to a specific folder it should be changed to something like that:

``` bash
STRING_TO_SIGN="PUT\n$CONTENT_MD5\n$CONTENT_TYPE\n$HEADER_DATE\n/$S3_BUCKET/$ARCHIVE_FOLDER/$ARCHIVE_NAME"
```

Then you also have to modify the URL at the end of the script to match your new signature.

```
https://$S3_BUCKET.s3-$S3_REGION.amazonaws.com/$ARCHIVE_NAME
```

should become 

```
https://$S3_BUCKET.s3-$S3_REGION.amazonaws.com/$ARCHIVE_FOLDER/$ARCHIVE_NAME
```

**Comment by RGBboy** [comment]
pull requests are welcome. You just need to make sure it allows for when $ARCHIVE_FOLDER is not present.

**Comment by RGBboy** [comment]
Sorry for the very delayed response on this. I have little time to spend on this as it is not needed in any of my current development. This library was originally built for my specific use case. I recommend writing your own if you would like a different behaviour. Feel free to fork this as a base.
