### ISSUE TITLE
Positional parameters

### ISSUE THREAD

**Issue by djsd123** [RGBboy/mongodb-s3-backup#7]
Hey Dude,

Probably worth mentioning that the parameters for username and password in your backup.sh are missing a preceding "-" character.  Script won't work without amending this. I'm using mongodb 3.x btw.

Thanks, Happy Holidays....

**Comment by RGBboy** [comment]
Thanks for the info.

This library was built for my specific use case back in the mongo 2.x days.  I recommend writing your own if you would like a different behaviour.
